projetEecole/src/main/java/com/ecole/backingbean/PersonneBackingBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ecole.backingbean;

import com.ecole.dao.PersonneDao;
import com.ecole.model.Admin;
import com.ecole.model.Adresse;
import com.ecole.model.Enseignant;
import com.ecole.model.Etudiant;
import com.ecole.model.LoginInfos;
import com.ecole.model.Personne;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.text.ParseException;
import java.util.logging.Level;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.model.DataModel;
import javax.servlet.http.HttpSession;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Administrateur
 */
public class PersonneBackingBean {

    private static final Logger LOGGER = LoggerFactory.getLogger(PersonneBackingBean.class);
    private String loginForm;
    private String passwordForm;
    private String passwordFormComfirm;
    private String nomForm;
    private String prenomForm;
    private String datenaissanceForm;

    public String getPasswordFormComfirm() {
        return passwordFormComfirm;
    }

    public void setPasswordFormComfirm(String passwordFormComfirm) {
        this.passwordFormComfirm = passwordFormComfirm;
    }
    private String emailForm;
    private Image photoForm;
    private String typePersonneForm;
    private String rueForm;
    private String cpForm;
    private String villeForm;
    private String PersonneRetourOKForm;

    public String getPersonneRetourOKForm() {
        return PersonneRetourOKForm;
    }

    public void setPersonneRetourOKForm(String PersonneRetourOKForm) {
        this.PersonneRetourOKForm = PersonneRetourOKForm;
    }

    public PersonneBackingBean() {
        LOGGER.info("création PersonneBackingBean init");
    }

    public String getLoginForm() {
        return loginForm;
    }

    public void setLoginForm(String loginForm) {
        LOGGER.info("création loginForm" + loginForm);
        this.loginForm = loginForm;
    }

    public String getPasswordForm() {
        return passwordForm;
    }

    public void setPasswordForm(String passwordForm) {
        LOGGER.info("création passwordForm" + passwordForm);
        this.passwordForm = passwordForm;
    }

    public String getNomForm() {
        return nomForm;
    }

    public void setNomForm(String nomForm) {
        LOGGER.info("création nomForm" + nomForm);
        this.nomForm = nomForm;
    }

    public String getPrenomForm() {
        return prenomForm;
    }

    public void setPrenomForm(String prenomForm) {
        LOGGER.info("création prenomForm" + prenomForm);
        this.prenomForm = prenomForm;
    }

    public String getDatenaissanceForm() {
        return datenaissanceForm;
    }

    public void setDatenaissanceForm(String datenaissanceForm) {
        LOGGER.info("création datenaissanceForm" + datenaissanceForm);
        this.datenaissanceForm = datenaissanceForm;
    }

    public String getEmailForm() {
        return emailForm;
    }

    public void setEmailForm(String emailForm) {
        LOGGER.info("création emailForm" + emailForm);
        this.emailForm = emailForm;
    }

    public Image getPhotoForm() {
        return photoForm;
    }

    public void setPhotoForm(Image photoForm) {
        LOGGER.info("création photoForm" + photoForm);
        this.photoForm = photoForm;
    }

    public String getTypePersonneForm() {
        return typePersonneForm;
    }

    public void setTypePersonneForm(String typePersonneForm) {
        LOGGER.info("création typePersonneForm" + typePersonneForm);
        this.typePersonneForm = typePersonneForm;
    }

    public String getRueForm() {
        return rueForm;
    }

    public void setRueForm(String rueForm) {
        LOGGER.info("création rueForm" + rueForm);
        this.rueForm = rueForm;
    }

    public String getCpForm() {
        return cpForm;
    }

    public void setCpForm(String cpForm) {
        LOGGER.info("création cpForm" + cpForm);
        this.cpForm = cpForm;
    }

    public String getVilleForm() {
        return villeForm;
    }

    public void setVilleForm(String villeForm) {
        LOGGER.info("création villeForm" + villeForm);
        this.villeForm = villeForm;
    }

    public void updateTypePersonneForm(ActionEvent event) {
        setTypePersonneForm(getTypePersonneForm());
        //LOGGER.info("updateSelected " + (Etudiant) dataModel.getRowData() + "-> Etudiant : " + selectedEtudiant.getNom());
    }

    public void reInitForm() {

        setNomForm("");
        setPrenomForm("");
        setEmailForm("");
        setLoginForm("");
        setPasswordForm("");
        setRueForm("");
        setCpForm("");
        setVilleForm("");
        setDatenaissanceForm("");
        setTypePersonneForm("");
        setPersonneRetourOKForm("");
    }

    public String addPersonne() {
        String ChaineRetour = "PersonneCree";
//        try {
        LOGGER.info("{} Debut de la création ");
        PersonneDao pDao = new PersonneDao();
//            DateFormat formatter ; 
//            Date dateFormatter ; 
//             formatter = new SimpleDateFormat("dd/MMM/yy");

//             dateFormatter = (Date)formatter.parse(getDatenaissanceForm());
        Personne newPersonne = new Personne();


        newPersonne.setNom(getNomForm());
        newPersonne.setPrenom(getPrenomForm());
        newPersonne.setPhoto(getPhotoForm());
        newPersonne.setDateNaissance(getDatenaissanceForm());
        newPersonne.setAdresse(new Adresse(getRueForm(), getCpForm(), getVilleForm()));
        newPersonne.setLoginInfoPersonne(new LoginInfos(getLoginForm(), getPersonneRetourOKForm()));
        newPersonne.setEmail(getEmailForm());
        newPersonne.setTypePersone(getTypePersonneForm());
        LOGGER.info("{} création de la newPersonne:" + newPersonne);
        pDao.createPersonne(newPersonne);
//        } catch (ParseException ex) {
//            java.util.logging.Logger.getLogger(PersonneBackingBean.class.getName()).log(Level.SEVERE, null, ex);
//        }
        setPersonneRetourOKForm("OK");
        reInitForm();
        return ChaineRetour;
    }

    public String doDisconnect() {
        ((HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext()
                .getSession(true)).invalidate();
        // Permet de rerouter l'utilisateur sur la page d'accueil
        return "../index.xhtml";
    }
}

projetEecole/src/main/webapp/pages/detailEtudiant.xhtml
<ui:composition template="../template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:f="http://java.sun.com/jsf/core"
                >
    <ui:define name="title">
        Detail Etudiant
    </ui:define>
    <ui:define name="content">
        <h2>
            <h:outputText id="etudiantTitle" value="Detail Etudiant"/>
        </h2>

        <h:form id="etudiantForm" rendered="#{!empty loginBean.loginForm}">

            <h:dataTable
                id="etudiant" 
                var="etudiant" 
                value="#{etudiantsBean.etudiantBB(loginBean.loginForm)}" 
                styleClass="table table-striped table-bordered"
                columnClasses="none,none,none,none">
                <tr>
                    <td>
                     <h:outputText id="labelEtudiantNom" value="Nom Etudiant"/> 
                     <h:inputText id="etudiantNom" value="#{etudiant.nomForm}"/>
                    </td>
                </tr>
            </h:dataTable>
        </h:form>
    </ui:define>
    <ui:define name="footer">
        Copyright Pandas
    </ui:define>    
</ui:composition>    

projetEecole/src/main/webapp/pages/formulaireCreation.xhtml
<ui:composition template="../template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:f="http://java.sun.com/jsf/core"
                >
    <ui:define name="title">
        Detail Etudiant
    </ui:define>
    <ui:define name="content">
        <h2>
            <h:outputText id="CreatPersonneTitle" value="Creation de personne"/>
        </h2>
        <h:panelGroup id="CreeaOK" rendered="#{!empty personneBean.personneRetourOKForm}">

            <h:outputText id="CreatOKTitle" value="Creation de personne Réussie..."/>

        </h:panelGroup>
        <h:form id="CreatPersonneForm">

            <h:selectOneRadio id="typePers" value="#{personneBean.typePersonneForm}" styleClass=".iceSelOneRb table td" required="true" 
                              requiredMessage="#{messages.required_value_error}" > 

                <f:selectItem id="Type1" itemLabel="Administrateur" itemValue="ADM" />
                <f:selectItem id="Type2" itemLabel="Enseignant" itemValue="ENS" />
                <f:selectItem id="Type3" itemLabel="Etudiant" itemValue="ETU" />

            </h:selectOneRadio> 
            <h:message for="CreatPersonneForm:typePers" errorClass="text-error"/>
            <table>                
                <tr>
                    <td>
                        <h:outputText id="labelPersonneNom" value="Nom"/> 
                    </td>
                    <td>
                        <h:inputText id="PersonneNom" value="#{personneBean.nomForm}" required="true" 
                                     requiredMessage="#{messages.required_value_error}" /> 

                        <h:message for="CreatPersonneForm:PersonneNom" errorClass="text-error"/>
                    </td>
                    <td></td>
                    <td>
                        <h:outputText id="labelPersonnePrenom" value="Prénom"/> 
                    </td>
                    <td>
                        <h:inputText id="personnePrenom" value="#{personneBean.prenomForm}" required="true" 
                                     requiredMessage="#{messages.required_value_error}" /> 

                        <h:message for="CreatPersonneForm:personnePrenom" errorClass="text-error"/>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td>
                        <h:outputText id="labelPersonneEmail" value="Email"/> 
                    </td>
                    <td>
                        <h:inputText id="personneEmail" value="#{personneBean.emailForm}"/>
                    </td>
                    <td></td>
                    <!--                    <td>
                                            <h:outputText id="labelPersonnePhoto" value="Photo"/> 
                                        </td>
                                        <td>
                                            <h:inputText id="personnePhoto" value="#{personneBean.photoForm}"/>
                                        </td>-->
                    <td></td>
                </tr>
                <tr>
                    <td>
                        <h:outputText id="labelPersonneRue" value="rue"/> 
                    </td>
                    <td>
                        <h:inputText id="PersonneRue" value="#{personneBean.rueForm}" required="true" 
                                     requiredMessage="#{messages.required_value_error}" /> 

                        <h:message for="CreatPersonneForm:PersonneRue" errorClass="text-error"/>
                    </td>
                    <td></td>
                    <td>
                        <h:outputText id="labelPersonneCP" value="Code Postal"/> 
                    </td>
                    <td>
                        <h:inputText id="personneCP" value="#{personneBean.cpForm}" required="true" 
                                     requiredMessage="#{messages.required_value_error}" /> 

                        <h:message for="CreatPersonneForm:personneCP" errorClass="text-error"/>
                    </td>                
                    <td>
                        <h:outputText id="labelPersonneVille" value="Ville"/> 
                    </td>
                    <td>
                        <h:inputText id="personneVille" value="#{personneBean.villeForm}" required="true" 
                                     requiredMessage="#{messages.required_value_error}" /> 

                        <h:message for="CreatPersonneForm:personneVille" errorClass="text-error"/>
                    </td>
                </tr>
                <h:panelGroup id="datePers" >                 
                    <tr>
                        <td>
                            <h:outputText id="labelPersonneDateNaiss" value="Date de naissance"/> 
                        </td>
                        <td>
                            <h:inputText id="personneDateNaiss" value="#{personneBean.datenaissanceForm}" required="true" 
                                         requiredMessage="#{messages.required_value_error}" /> 

                            <h:message for="CreatPersonneForm:personneDateNaiss" errorClass="text-error"/>
                        </td>
                    </tr>
                </h:panelGroup>
                <tr>
                    <td>
                        <h:outputText id="labelPersonneLogin" value="Login Personne"/>
                    </td>
                    <td>
                        <h:inputText id="personneLogin" value="#{personneBean.loginForm}" required="true" 
                                     requiredMessage="#{messages.required_value_error}" /> 

                        <h:message for="CreatPersonneForm:personneLogin" errorClass="text-error"/>
                    </td>
                    <td></td>
                    <td>
                        <h:outputText id="labelPersonnePassword" value="Password Personne"/> 
                    </td>
                    <td>
                        <h:inputSecret id="personnePassword" value="#{personneBean.passwordForm}" required="true" 
                                       requiredMessage="#{messages.required_value_error}" /> 

                        <h:message for="CreatPersonneForm:personnePassword" errorClass="text-error"/>
                    </td>
                    <td>
                        <h:outputText id="labelPersonnePasswordConfirm" value="Confirmer password"/> 
                    </td>
                    <td>
                        <h:inputSecret id="personnePasswordConfirm" value="#{personneBean.passwordFormComfirm}"  required="true" 
                                       requiredMessage="#{messages.required_value_error}" /> 

                        <h:message for="CreatPersonneForm:personnePasswordConfirm" errorClass="text-error"/>
                    </td> 
                </tr>                
            </table>
            <h:inputHidden id="personneRetourOKForm" value="#{personneBean.personneRetourOKForm}"/>
            <h:commandButton id="addPers" value="#{messages.label_validate}" action="#{personneBean.addPersonne()}"/>
                        <h:commandLink action="#{personneBean.doDisconnect()}">
                Se déconnecter
            </h:commandLink>
        </h:form>
        <script type="text/javascript">
            var adm = document.getElementById("CreatPersonneForm:typePers:0");
            var ens = document.getElementById("CreatPersonneForm:typePers:1");            
            var etu = document.getElementById("CreatPersonneForm:typePers:2");
            var labelDateNaissance = document.getElementById("CreatPersonneForm:labelPersonneDateNaiss");
            var DateNaissance = document.getElementById("CreatPersonneForm:personneDateNaiss");
            
            labelDateNaissance.style.visibility='hidden';
            DateNaissance.style.visibility='hidden';
            
            adm.onclick = function(){                
                labelDateNaissance.style.visibility='hidden';
                DateNaissance.style.visibility='hidden';
            };
            ens.onclick = function(){                
                labelDateNaissance.style.visibility='hidden';
                DateNaissance.style.visibility='hidden';
            };
            
            etu.onclick = function(){                
                labelDateNaissance.style.visibility='visible';
                DateNaissance.style.visibility='visible';
            };  
             
            var boutonValider = document.getElementById("CreatPersonneForm:addPers");
                   
            boutonValider.onclick = function(){
                var passwordini = document.getElementById("CreatPersonneForm:personnePassword");
                var passwordConfirm = document.getElementById("CreatPersonneForm:personnePasswordConfirm");
                var testPass1="" + passwordini.value;
                var testPass2="" + passwordConfirm.value;
                
                alert("pass1:" + testPass1);
                alert("pass2:" + testPass2);
	
                if (testPass1===testPass2){
		
                    /*document.getElementById("divPasswordCrypte").innerHTML = chaine;*/	
                    document.getElementById("CreatPersonneForm:personneRetourOKForm").value=hex_sha1(hex_md5(passwordini));
                    alert(document.getElementById("CreatPersonneForm:personneRetourOKForm").value);
                }
                else{
                    alert("les mot de passe ne sont pas identiques");
                    passwordini.value="";
                    passwordConfirm.value="";
                }
            }

            function cryptagePandas(){
                var val=document.getElementById("CreatPersonneForm:passwordini").value;
                document.getElementById("CreatPersonneForm:passwordini").value=hex_sha1(hex_md5(val));
            }
        </script>
    </ui:define>
    <ui:define name="footer">
        Copyright Pandas
    </ui:define>    
</ui:composition>    

projetEecole/src/main/webapp/pages/listePersonnes.xhtml
<ui:composition template="../template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:f="http://java.sun.com/jsf/core"
                >
    <ui:define name="title">
        Liste des étudiants
    </ui:define>
    <ui:define name="content">
        <h2>
            <h:outputText id="listeEtudiantsTitle" value="Listes des Etudiants"/>
        </h2>

        <h:form id="listeEtudiants" rendered="#{!empty loginBean.loginForm}">

            <h:dataTable
                id="listeEtudiants" 
                var="etudiant" 
                value="#{listeBean.dataModel}" 
                styleClass="table table-striped table-bordered"
                columnClasses="col1,col2,col3,col4,col5,col6,col7">
                <h:column id="detailColumn">
                    <h:commandLink id="detailLink" value="Detail" actionListener="#{listeBean.updateSelected}"/>
                </h:column>
                <h:column id="nomColumn">
                    <f:facet name="header">
                        <h:outputText id="nomText" value="Nom"/>
                    </f:facet>
                    <h:outputText id="nomValue" value="#{etudiant.nom}"/>
                </h:column>
                <h:column id="prenomColumn">
                    <f:facet name="header">
                        <h:outputText id="prenomText" value="Prenom"/>
                    </f:facet>
                    <h:outputText id="prenomValue" value="#{etudiant.prenom}"/>
                </h:column>

                <h:column id="datenaissanceColumn">
                    <f:facet name="header">
                        <h:outputText id="datenaissanceText" value="DateNaissance"/>
                    </f:facet>
                    <h:outputText id="datenaissanceValue" value="#{etudiant.dateNaissance}">
                        <f:convertDateTime type="date" pattern="dd/MMMM/yyyy"/>
                    </h:outputText>
                </h:column>
                <h:column id="emailColumn">
                    <f:facet name="header">
                        <h:outputText id="emailText" value="Email"/>
                    </f:facet>
                    <h:outputText id="emailValue" value="#{etudiant.email}"/>
                </h:column>
                <h:column id="modifColumn">
                    <h:commandLink id="modifLink" value="Modifier" actionListener="#{listeBean.updateSelected}"/>
                </h:column>
                <h:column id="suppColumn">
                    <h:commandLink id="suppLink" value="Supprimer" actionListener="#{listeBean.suppEtudiant}"/>
                </h:column>
            </h:dataTable>
            
            
            
            
            <h:panelGroup rendered="#{!empty listeBean.selectedEtudiant}">
                <!--<h:form id="detailUserForm"> -->
                 <p> Nom :  #{listeBean.selectedEtudiant.nom}</p>
                <p> prenom :  #{listeBean.selectedEtudiant.prenom}</p>
                
            </h:panelGroup>
            <h:commandLink action="#{listeBean.doDisconnect()}">
                Se déconnecter
            </h:commandLink>
        </h:form>
    </ui:define>
    <ui:define name="footer">
        Copyright Pandas
    </ui:define>    
</ui:composition>    